# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'SuperBusDriver' do

pod 'Alamofire'
pod 'MBProgressHUD', '~> 0.9'

end

target 'SuperBusDriverTests' do

end

